name: Detect Issues
on:
  issues:
    types:
      - opened
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output Issues
        run: |
          echo "${{ toJSON(github.event) }}"